name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          build-root-directory: app
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install coverage
          pip install poetry
          pip install flake8
          poetry add pytest-cov
          make build
          make package-install
          make publish
          python3 -m pip install pytest
      - name: Run linter and pytest
        run: |
          make check
          make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v8.0.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          PAAMBATI_SOURCE_PATH: src/main/python
        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{github.workspace}}/app/build/reports/paambati/test/paambatiTestReport.xml:paambati
          debug: true
2141221024 · Korvo-iam/python-project-50@2f3a2a7

